server:
   port: 8081
spring:
   application:
      name: bank
   datasource:
      url: jdbc:postgresql://localhost:5432/bank
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver
   jpa:
      hibernate:
         ddl-auto: update
   sql:
      init:
         mode: always
resilience4j:
   retry:
      instances:
         authorizeClient:
            maxAttempts: 3
            waitDuration: 500ms
         notifyClient:
            maxAttempts: 3
            waitDuration: 500ms
